name: 'Build and deploy Firebase - Functions + Storage + Firestore or everything with yarn'
author: 'Amar Sharma <amarsharma.hacker@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Functions, Storage, and Firestore'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'orange'
