name: 'Deploy Firebase - Functions + Storage + Firestore'
author: 'Ivo Ilic <admin@ivoilic.com>'
description: 'A GitHub Action to deploy to Firebase Functions, Storage, and Firestore'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'orange'
